---
########
iscreen:
########
  ########
  ########
  cluster:
    ########
    test1:
      library:
        DB.sdf.gz
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits

    ########
    test2:
      library:
        DB.sdf.gz
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB-allow-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

    ########
    test3:
      library:
        BioDesign_48291.sdf.gz
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-BioDesign_48291.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test4:
      library:
        BioDesign_48291.sdf.gz
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-BioDesign_48291-allow-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

    ########
    test5:
      library:
        BioDesign_48291.sdf.gz
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-BioDesign_48291.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test6:
      library:
        BioDesign_48291.sdf.gz
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-BioDesign_48291-allow-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits


  ########
  ########
  local:
    ########
    test1:
      library:
        actives_final_1XL2.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-actives_final_1XL2-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test2:
      library:
        decoys_final_1XL2.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-decoys_final_1XL2-omit-3.sdf
      options:
        --allow-omit 3
      evaluate:
        time
        hits
    
    ########
    test3:
      library:
        decoys_final_1XL2.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-decoys_final_1XL2-omit-4.sdf
      options:
        --allow-omit 4
      evaluate:
        time
        hits

    ########
    test4:
      library:
        actives_final_3TOF.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-actives_final_3TOF.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test5:
      library:
        actives_final_3TOF.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-actives_final_3TOF-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test6:
      library:
        actives_final_3TOF.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-actives_final_3TOF-omit-2.sdf
      options:
        --allow-omit 2
      evaluate:
        time
        hits

    ########
    test7:
      library:
        decoys_final_3TOF.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-decoys_final_3TOF.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test8:
      library:
        decoys_final_3TOF.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-decoys_final_3TOF-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test9:
      library:
        decoys_final_3TOF.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-decoys_final_3TOF-omit-2.sdf
      options:
        --allow-omit 2
      evaluate:
        time
        hits

    ########
    test10:
      library:
        decoys_final_3KBA.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-decoys_final_3KBA.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test11:
      library:
        actives_final_3KBA.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-decoys_final_3KBA.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits

    ########
    test12:
      library:
        decoys_final_3KBA.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-decoys_final_3KBA-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test13:
      library:
        actives_final_3KBA.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-decoys_final_3KBA-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits



########
espresso:
########
  ########
  test1:
    db:
      some-things
    options:
      some-things
  
########
idbgen:
########
  ########
  ########
  local:
    ########
    test1:
      input:
        actives_final_1XL2.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        actives_final_1XL2.ldb
      evaluate:
        time
        duplicate
        inserted
        failed
    
    ########
    test2:
      input:
        decoys_final_1XL2.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        decoys_final_1XL2.ldb
      evaluate:
        time
        duplicate
        inserted
        failed

    ########
    test3:
      input:
        actives_final_3TOF.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        actives_final_3TOF.ldb
      evaluate:
        time
        duplicate
        inserted
        failed
    
    ########
    test4:
      input:
        decoys_final_3TOF.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        decoys_final_3TOF.ldb
      evaluate:
        time
        duplicate
        inserted
        failed


    ########
    test5:
      input:
        actives_final_3KBA.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        actives_final_3KBA.ldb
      evaluate:
        time
        duplicate
        inserted
        failed
    
    ########
    test6:
      input:
        decoys_final_3KBA.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        decoys_final_3KBA.ldb
      evaluate:
        time
        duplicate
        inserted
        failed
  ########
  ########
  cluster:
    ########
    test1:
      input:
        DB.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 1000'
      output:
        DB.ldb
      evaluate:
        time
        duplicate
        failed

    ########
    test2:
      input:
        BioDesign_48291.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 1000'
      output:
        DB.ldb
      evaluate:
        time
        duplicate
        failed

    ########
    test3:
      input:
        BioDesign_48291.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 2000'
      output:
        DB.ldb
      evaluate:
        time
        duplicate
        failed

    ########
    test4:
      input:
        BioDesign_48291.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 3000'
      output:
        DB.ldb
      evaluate:
        time
        duplicate
        failed


...