---
################
iscreen:
################
  ################
  ################
  cluster:
    ################
    test1:
      library:
        DB1_7000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB1_7000.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits

    ########
    test2:
      library:
        DB_7000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB_7000-allow-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

    ########
    test3:
      library:
        DB2_50000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB2_50000.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test4:
      library:
        DB2_50000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB2_50000-allow-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

    ########
    test5:
      library:
        DB2_50000.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-DB2_50000.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test6:
      library:
        DB2_50000.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-DB2_50000-allow-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits


  ################
  ################
  local:
    ########
    test1:
      library:
        DB2_50000.ldb
      ph:
        1XL2.pml
      hitlist:
        DB2_50000.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test2:
      library:
        1XL2_decoys_40000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-1XL2_decoys_40000-omit-3.sdf
      options:
        --allow-omit 3
      evaluate:
        time
        hits
    
    ########
    test3:
      library:
        1XL2_decoys_40000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-1XL2_decoys_40000-omit-4.sdf
      options:
        --allow-omit 4
      evaluate:
        time
        hits

    ########
    test4:
      library:
        3KBA_actives_400.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-3KBA_actives_400.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test5:
      library:
        3TOF_actives_1400.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-3TOF_actives_1400-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test6:
      library:
        3TOF_actives_1400.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-3TOF_actives_1400-omit-2.sdf
      options:
        --allow-omit 2
      evaluate:
        time
        hits

    ########
    test7:
      library:
        3TOF_decoys_40000.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-3TOF_decoys_40000.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test8:
      library:
        3TOF_decoys_40000.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-3TOF_decoys_40000-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test9:
      library:
        3TOF_decoys_40000.ldb
      ph:
        3TOF.pml
      hitlist:
        3TOF-vs-3TOF_decoys_40000-omit-2.sdf
      options:
        --allow-omit 2
      evaluate:
        time
        hits

    ########
    test10:
      library:
        3KBA_decoys_15000.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-3KBA_decoys_15000.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits
    
    ########
    test11:
      library:
        3KBA_actives_400.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-3KBA_actives_400.sdf
      options:
        --allow-omit 0
      evaluate:
        time
        hits

    ########
    test12:
      library:
        3KBA_decoys_15000.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-3KBA_decoys_15000-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits
    
    ########
    test13:
      library:
        3KBA_actives_400.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-3KBA_actives_400-omit-1.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

    ########
    test14:
      library:
        DB1_7000.ldb
      ph:
        3KBA.pml
      hitlist:
        3KBA-vs-DB1_7000.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

    ########
    test15:
      library:
        DB1_7000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB1_7000.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

    ########
    test16:
      library:
        DB2_50000.ldb
      ph:
        1XL2.pml
      hitlist:
        1XL2-vs-DB2_50000.sdf
      options:
        --allow-omit 1
      evaluate:
        time
        hits

################
espresso:
################
  ################
  test1:
    db:
      some-things
    options:
      some-things
  
################
idbgen:
################
  ################
  ################
  local:
    ################
    test1:
      input:
        1XL2_actives_1400.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        1XL2_actives_1400.ldb
      evaluate:
        time
        duplicate
        inserted
        failed
    
    ########
    test2:
      input:
        1XL2_decoys_40000.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        1XL2_decoys_40000.ldb
      evaluate:
        time
        duplicate
        inserted
        failed

    ########
    test3:
      input:
        3TOF_actives_1400.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        3TOF_actives_1400.ldb
      evaluate:
        time
        duplicate
        inserted
        failed
    
    ########
    test4:
      input:
        3TOF_decoys_40000.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        3TOF_decoys_40000.ldb
      evaluate:
        time
        duplicate
        inserted
        failed

    ########
    test5:
      input:
        3KBA_actives_400.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        3KBA_actives_400.ldb
      evaluate:
        time
        duplicate
        inserted
        failed
    
    ########
    test6:
      input:
        3KBA_decoys_15000.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        3KBA_decoys_15000.ldb
      evaluate:
        time
        duplicate
        inserted
        failed

    ########
    test7:
      input:
        DB1_7000.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        DB1_7000.ldb
      evaluate:
        time
        duplicate
        inserted
        failed


    ########
    test8:
      input:
        DB2_50000.sdf.gz
      options:
        '--confgen-type icon-fast'
      output:
        DB2_50000.ldb
      evaluate:
        time
        duplicate
        inserted
        failed


  ################
  ################
  cluster:
    ################
    test1:
      input:
        DB1_7000.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 1000'
      output:
        DB1_7000.ldb
      evaluate:
        time
        duplicate
        failed

    ########
    test2:
      input:
        DB2_50000.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 1000'
      output:
        DB2_50000.ldb
      evaluate:
        time
        duplicate
        failed

    ########
    test3:
      input:
        DB2_50000.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 2000'
      output:
        DB2_50000.ldb
      evaluate:
        time
        duplicate
        failed

    ########
    test4:
      input:
        DB2_50000.sdf.gz
      options:
        '--confgen-type icon-fast --qsub-chunk-size 3000'
      output:
        DB2_50000.ldb
      evaluate:
        time
        duplicate
        failed


...